### ISSUE TITLE
Installed successfully but will not launch - 

### ISSUE THREAD

**Issue by wgregori** [DissentDifference/DarkWallet#2]
I've installed darkwallet and the install log seems in good order... but the wallet will no launch...  here's the terminal read out:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/home/wayne/darkwallet_desktop/darkwallet/darkwallet-daemon.py", line 4, in <module>
    import darkwallet
  File "/home/wayne/darkwallet_desktop/darkwallet/darkwallet/__init__.py", line 1, in <module>
    from darkwallet.gateway import start
  File "/home/wayne/darkwallet_desktop/darkwallet/darkwallet/gateway.py", line 9, in <module>
    from libbitcoin.server_fake_async import TornadoContext
  File "/home/wayne/darkwallet_desktop/python-libbitcoin/libbitcoin/__init__.py", line 1, in <module>
    import libbitcoin.bc
  File "/home/wayne/darkwallet_desktop/python-libbitcoin/libbitcoin/bc/__init__.py", line 2, in <module>
    from libbitcoin.bc.base_10 import btc_decimal_places, mbtc_decimal_places, \
  File "/home/wayne/darkwallet_desktop/python-libbitcoin/libbitcoin/bc/base_10.py", line 1, in <module>
    from libbitcoin.bc.config import ffi, lib
  File "/home/wayne/darkwallet_desktop/python-libbitcoin/libbitcoin/bc/config.py", line 2, in <module>
    lib = ffi.dlopen("libbitcoin-c.so")
OSError: cannot load library 'libbitcoin-c.so': libbitcoin-c.so: cannot open shared object file: No such file or directory

> darkwallet-electron-ui@0.0.1 dev /home/wayne/darkwallet_desktop/darkwallet-electron-ui
> npm run hot-server -- --start-hot


> darkwallet-electron-ui@0.0.1 hot-server /home/wayne/darkwallet_desktop/darkwallet-electron-ui
> cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"

sh: 1: cross-env: not found

npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "hot-server" "--" "--start-hot"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! darkwallet-electron-ui@0.0.1 hot-server: `cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register server.js "--start-hot"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the darkwallet-electron-ui@0.0.1 hot-server script 'cross-env NODE_ENV=developmen

**Comment by luminaryphi** [comment]
I also have this problem. It's in my launcher but when I click it nothing happens.
